---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
platforms:
  - name: instance
    image: solita/ubuntu-systemd:18.04
    dockerfile: Dockerfile.j2
    privileged: true
    command: /sbin/init
scenario:
  name: theme-replacements
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - destroy
provisioner:
  name: ansible
  lint: |
    ansible-lint
verifier:
  name: ansible
  lint: |
    flake8
