---
- name: Make Checkout Path for Enketo Repo
  file:
    state: directory
    path: "{{ enketo_checkout_path }}"
    owner: "{{ enketo_user }}"
    group: "{{ enketo_group }}"
    recurse: yes

- name: Clone Enketo GIT Repository
  become: true
  become_user: "{{ enketo_user }}"
  git:
    repo: "{{ enketo_git_url }}"
    dest: "{{ enketo_checkout_path }}"
    version: "{{ enketo_git_branch }}"
    recursive: yes
    update: yes

- name: Copy enketo config to config directory
  template:
    src: templates/enketo/config.json.j2
    dest: "{{ enketo_checkout_path }}/packages/enketo-express/config/config.json"
    owner: "{{ enketo_user }}"
    group: "{{ enketo_group }}"
    mode: "0644"

- name: Replace Enketo offline color for form header
  become: true
  become_user: "{{ enketo_user }}"
  ansible.builtin.replace:
    path: "{{ enketo_checkout_path }}/packages/enketo-express/app/views/styles/component/_form_header.scss"
    regexp: "^\\$offline-color: .*$"
    replace: "$offline-color: {{ enketo_offline_color_hexcode }};"
  when: enketo_offline_color_hexcode is defined and enketo_offline_color_hexcode

- name: Replace Enketo brand color for theme
  become: true
  become_user: "{{ enketo_user }}"
  ansible.builtin.replace:
    path: "{{ enketo_checkout_path }}/packages/enketo-express/app/views/styles/theme-{{ item }}/_variables.scss"
    regexp: "^\\$brand-primary-color: .*$"
    replace: "$brand-primary-color: {{ enketo_primary_color_hexcode }};"
  with_items:
    - "kobo"
    - "formhub"
  when:
    - enketo_primary_color_hexcode is defined and enketo_primary_color_hexcode

- name: Ensure offline color is set for theme
  become: true
  become_user: "{{ enketo_user }}"
  ansible.builtin.lineinfile:
    path: "{{ enketo_checkout_path }}/packages/enketo-express/app/views/styles/component/_form_header.scss"
    regexp: "^\\$offline-color: .*$"
    line: "$offline-color: {{ enketo_offline_color_hexcode }};"
  when:
    - enketo_offline_color_hexcode is defined and enketo_offline_color_hexcode

- name: Make the new codebase current
  file:
    force: yes
    state: link
    dest: "{{ enketo_codebase_path }}"
    src: "{{ enketo_checkout_path }}"

- name: Install npm Dependencies in package.json
  become: true
  become_user: "{{ enketo_user }}"
  shell: "env PATH=/home/enketo/.nvm/versions/node/{{ enketo_node_version }}/bin:$PATH yarn workspace enketo-express install"
  args:
    chdir: "{{ enketo_checkout_path }}"

- name: Install npm Dependencies in package.json
  become: true
  become_user: "{{ enketo_user }}"
  shell: "env PATH=/home/enketo/.nvm/versions/node/{{ enketo_node_version }}/bin:$PATH yarn build"
  args:
    chdir: "{{ enketo_checkout_path }}"

- name: delete specific enketo pm2 process
  become: true
  become_user: "{{ enketo_user }}"
  command: "{{ enketo_pm2_path }} delete {{ enketo_user }}"
  # this command fails if the process has not yet been started
  ignore_errors: yes
  environment:
    PATH: "{{ enketo_node_dir }}/bin:{{ ansible_env.PATH }}"
    HOME: "{{ enketo_home }}"
  tags:
    - run-app

- name: Setup SystemD unit
  include_tasks: setup-systemd-unit.yml

# TODO: Add in the docs that we only support ubuntu > 14
- name: Run handler services
  include_tasks: handlers/main.yml

