---
- name: Install Node Version Manager
  include_role:
    name: onaio.nvm
  become: true
  become_user: "{{ enketo_user }}"
  vars:
    nvm_user: "{{ enketo_user }}"
    nvm_group: "{{ enketo_group }}"
    nvm_node_version: "{{ enketo_node_version }}"
    nvm_install_path: "{{ enketo_nvm_root }}"
    nvm_node_dir: "{{ enketo_node_dir }}"
    nvm_npm_path: "{{ enketo_npm_path }}"
    nvm_version: "{{ enketo_nvm_version }}"

- name: Install npm global packages
  shell: "{{ enketo_npm_path }} install -g {{ item.package }}@{{ item.version }}"
  with_items:
    - { "package":"grunt-cli", "version":"{{ enketo_grunt_cli_version }}" }
    - { "package":"bower", "version":"{{ enketo_bower_version }}" }
    - { "package":"mocha", "version":"{{ enketo_mocha_version }}" }
    - { "package":"pm2", "version":"{{ enketo_pm2_version }}" }
  environment:
    PATH: "{{ enketo_node_dir }}/bin:{{ ansible_env.PATH }}"
