---
- name: reload systemctl
  command: systemctl daemon-reload
  tags:
    - skip_ansible_lint

- name: reload enketo
  service:
    name: "{{ enketo_system_user }}"
    state: restarted

- name: reload nginx
  debug:
    msg: "dummy reload nginx task"
  when: test
