{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}


RUN apt-get update && \
      apt-get -y install sudo

ENV ANSIBLE_USER=ansible
RUN set -xe
RUN groupadd -r ${ANSIBLE_USER}
RUN useradd -m -g ${ANSIBLE_USER} ${ANSIBLE_USER}
RUN echo "${ANSIBLE_USER} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

EXPOSE 8005
