---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: solita/ubuntu-systemd:18.04
    dockerfile: Dockerfile.j2
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
verifier:
  name: ansible
