---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Populate config file.
      stat:
        path: "/home/enketo/app/config/config.json"
      register: config_file

    - name: Fail if config file does not exist
      fail:
      when: not config_file.stat.exists

    - name: Check that host file belongs to correct group
      fail:
      when: not config_file.stat.gr_name == "www-data"

    - name: Check that host file belongs to correct user
      fail:
      when: not config_file.stat.pw_name == "enketo"

    - name: Ensure submissions configuration is set to lowercase
      lineinfile:
        name: "/home/enketo/app/config/config.json"
        line: '        "submissions": true'
        state: present
      check_mode: yes
      register: conf
      failed_when: (conf is changed) or (conf is failed)
